title: A Short Introduction to Parallel Computing
repository:
        url: https://github.com/Cirdans-Home/intrompi
        branch: main
execute:
        execute_notebooks: force

launch_buttons:
        notebook_interface: "jupyterlab"

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

parse:
  myst_enable_extensions:
          - amsmath
          - dollarmath
