title: A Short Introduction to Parallel Computing
author: Fabio Durastante
repository:
        url: https://github.com/Cirdans-Home/intrompi
        branch: main

html:
        use_repository_button: true
        use_issues_button: true
        use_edit_page_button: true
        base_url: https://cirdans-home.github.io/intrompi

exclude_patterns: [_build]
only_build_toc_files: true
execute:
        execute_notebooks: force

launch_buttons:
        notebook_interface: "jupyterlab"

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

parse:
  myst_enable_extensions:
          - amsmath
          - dollarmath
